name: Build e Deploy para KingHost

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instala dependências
        run: npm install

      - name: Build do projeto
        run: npm run build

      - name: Instala lftp
        run: sudo apt-get install -y lftp

      - name: Debug caminhos FTP
        run: |
          lftp -d -e "
            set ssl:verify-certificate no;
            set ftp:passive-mode yes;
            set net:timeout 10;
            open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }};
            ls -la;
            echo '---';
            ls -la public_html;
            echo '---';
            ls -la www;
            echo '---';
            ls -la Www;
            quit
          " 2>&1 || true
